### ISSUE TITLE
I modified a signature and it still valid

### ISSUE THREAD

**Issue by brunocasarotti** [ACken2/bip322#9]
Hey I am very confused how is possible that if I change some chars on the signature below it continues to be a valid signature

address=`bc1qfgn6k2fe4mvjxkcwa4tt4jphx8epg0r0f87squ`
message=`48656c6c6f20426974636f696e203230362e38342e3134372e3635`
signature=`H2l6+L8G24sBpB1+J1iwUv4/4LB0bba9bsxnopUbLNA2Qnf/JROsLJYUAVTF1dBfzCw69VBlOe9ehwQEEl5YbIY=`

modified and valid signatures
signature=`H2l6+L8G24sBpB1+J1iwUv4/4LB0bba9bsxnopUbLNA2Qnf/JROsLJYUAVTF1dBfzCw69VBlOe9ehwQEEl5YbIa=` (changed last letter by `a`)

signature=`a2l6+L8G24sBpB1+J1iwUv4/4LB0bba9bsxnopUbLNA2Qnf/JROsLJYUAVTF1dBfzCw69VBlOe9ehwQEEl5YbIa=` (changed first and last letter by `a`)

Can you clarify it for me please? I thought it would be invalid after the modification.

**Comment by ACken2** [comment]
Your first issue arises from the base64 encoding scheme, rather than the underlying signature verification process.

When you use a base64 decoder like this [one](https://base64.guru/converter/decode/hex), you'll notice that your initial signature "H2l6+L8G24sBpB1+J1iwUv4/4LB0bba9bsxnopUbLNA2Qnf/JROsLJYUAVTF1dBfzCw69VBlOe9ehwQEEl5YbIY=" decodes to the following hex:
```
1f697af8bf06db8b01a41d7e2758b052fe3fe0b0746db6bd6ecc67a2951b2cd0364277ff2513ac2c96140154c5d5d05fcc2c3af5506539ef5e870404125e586c86
```
Similarly, decoding your modified signature "H2l6+L8G24sBpB1+J1iwUv4/4LB0bba9bsxnopUbLNA2Qnf/JROsLJYUAVTF1dBfzCw69VBlOe9ehwQEEl5YbIa=" yields:
```
1f697af8bf06db8b01a41d7e2758b052fe3fe0b0746db6bd6ecc67a2951b2cd0364277ff2513ac2c96140154c5d5d05fcc2c3af5506539ef5e870404125e586c86
```
Since the underlying hex for both strings is identical, the signatures are equally valid.

The situation with your second signature is more nuanced. As of library version v1.1.1, this signature is deemed invalid:
```
const { Verifier } = require('bip322-js');

const address = "bc1qfgn6k2fe4mvjxkcwa4tt4jphx8epg0r0f87squ";
const message = "48656c6c6f20426974636f696e203230362e38342e3134372e3635";
const signature = "a2l6+L8G24sBpB1+J1iwUv4/4LB0bba9bsxnopUbLNA2Qnf/JROsLJYUAVTF1dBfzCw69VBlOe9ehwQEEl5YbIa=";

console.log(Verifier.verifySignature(address, message, signature)); // Error: Invalid signature parameter
```

However, verifybitcoinmessage.com considers this signature valid, utilizing a verification method outlined in the fallbackVerification function below. This method compensates for address type mismatches by replacing the first byte of the signature with integers ranging from 31 to 42. Therefore, even with the first byte altered, the website adjusts it during verification, ensuring validity:
```
fallbackVerification = (message, address, signature) => {
    let isValid = false;
    const flags = [...Array(12).keys()].map(i => i + 31);
    for (let flag of flags) {
      let flagByte = Buffer.alloc(1);
      flagByte.writeInt8(flag);
      let sigBuffer = Buffer.from(signature, 'base64').slice(1);
      sigBuffer = Buffer.concat([flagByte, sigBuffer]);
      let candidateSig = sigBuffer.toString('base64');
      try {
        isValid = bitcoinMessage.verify(message, address, candidateSig);
        if (isValid) break;
      } catch(e) {
      }
    }
    return isValid;
  }
```
This approach contrasts with the library's treatment of BIP-137 signatures, which rejects signatures whose first byte does not fall within the 27 to 42 range as mandated by the BIP137 standard.
